// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: grants.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createGrant = `-- name: CreateGrant :one
INSERT INTO grants (id, title, organization, amount, deadline, link, notes, status, updated_at, created_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    NOW(),
    NOW()
)
RETURNING id, title, organization, amount, deadline, link, notes, status, created_at, updated_at
`

type CreateGrantParams struct {
	Title        string
	Organization string
	Amount       int32
	Deadline     time.Time
	Link         sql.NullString
	Notes        sql.NullString
	Status       string
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (Grant, error) {
	row := q.db.QueryRowContext(ctx, createGrant,
		arg.Title,
		arg.Organization,
		arg.Amount,
		arg.Deadline,
		arg.Link,
		arg.Notes,
		arg.Status,
	)
	var i Grant
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Organization,
		&i.Amount,
		&i.Deadline,
		&i.Link,
		&i.Notes,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
