// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Grant struct {
	ID           uuid.UUID
	Title        string
	Organization string
	Amount       int32
	Deadline     time.Time
	Link         sql.NullString
	Notes        sql.NullString
	Status       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
